title: <p style="text-align: center;">Sienka Dounia</p>
logo: assets/images/headshot.png
description: I am deeply passionate about Science, Technology, Engineering, and Mathematics (STEM). Every day, I dedicate my skills, whether in IT, Science, Accounting, Project Management or Blogging, towards the collective goal of building a brighter and more promising world
show_downloads: false
theme: jekyll-theme-minimal
